### ISSUE TITLE
I am refering to the last article and i am suggesting a small improvements.

### ISSUE THREAD

**Issue by Raffaello** [nghenglim/database_benchmark#2]
Hi,
 you should even provide the schema where you benchmark against.
for example the LIKE query it is fine, but in a production it will be replaced by MATCH AGAINST fulltext index. so i think you miss this test.
even more it depends a lot on indexes too and some internal configuration.

anyway it is nice to have a quick overview.

**Comment by nghenglim** [comment]
Just to point out that sometimes even in production LIKE won't be replaced with MATCH AGAINST because PO/user want to maintain the same way wildcard search do.

Fulltext search is still a useful query though.

**Comment by Raffaello** [comment]
@nghenglim yep, unfortuantely you're right.  :+1:  :)
